language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script:
- PINS="wodan.dev:." bash -ex .travis-opam.sh
env:
  global:
  - ALCOTEST_SHOW_ERRORS=1

matrix:
  include:
  - env: OCAML_VERSION=4.11 PACKAGE=wodan
  - env: OCAML_VERSION=4.11 PACKAGE=wodan-unix
  - env: OCAML_VERSION=4.11 PACKAGE=wodan-irmin
  - env: OCAML_VERSION=4.10 PACKAGE=wodan
  - env: OCAML_VERSION=4.10 PACKAGE=wodan-unix
  - env: OCAML_VERSION=4.10 PACKAGE=wodan-irmin
  - env: OCAML_VERSION=4.09 PACKAGE=wodan
  - env: OCAML_VERSION=4.09 PACKAGE=wodan-unix
  - env: OCAML_VERSION=4.09 PACKAGE=wodan-irmin
  - env: OCAML_VERSION=4.08 PACKAGE=wodan
  - env: OCAML_VERSION=4.08 PACKAGE=wodan-unix
  - env: OCAML_VERSION=4.08 PACKAGE=wodan-irmin
os:
  - linux
