language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script:
- export PINS="$({ echo wodan.dev:.; for op in vendor/*/*.opam; do echo "$op" |sed -re 's#(vendor/.*/)(.*)\.opam#\2.dev:\1#'; done; } |xargs)"
- bash -ex .travis-opam.sh
env:
  global:
  - ALCOTEST_SHOW_ERRORS=1

matrix:
  include:
  - env: OCAML_VERSION=4.09 PACKAGE=wodan
  - env: OCAML_VERSION=4.09 PACKAGE=wodan-unix
  - env: OCAML_VERSION=4.09 PACKAGE=wodan-irmin
  - env: OCAML_VERSION=4.08 PACKAGE=wodan
  - env: OCAML_VERSION=4.08 PACKAGE=wodan-unix
  - env: OCAML_VERSION=4.08 PACKAGE=wodan-irmin
  - env: OCAML_VERSION=4.07 PACKAGE=wodan
  - env: OCAML_VERSION=4.07 PACKAGE=wodan-unix
  - env: OCAML_VERSION=4.07 PACKAGE=wodan-irmin
  - env: OCAML_VERSION=4.06 PACKAGE=wodan
  - env: OCAML_VERSION=4.06 PACKAGE=wodan-unix
  - env: OCAML_VERSION=4.06 PACKAGE=wodan-irmin
  #- env: OCAML_VERSION=4.05 PACKAGE=wodan
  #- env: OCAML_VERSION=4.05 PACKAGE=wodan-unix
  #- env: OCAML_VERSION=4.05 PACKAGE=wodan-irmin
  allow_failures:
# Ancient stuff of dubious use, someone wanted it for a BSD I think
  - env: OCAML_VERSION=4.05 PACKAGE=wodan
  - env: OCAML_VERSION=4.05 PACKAGE=wodan-unix
  - env: OCAML_VERSION=4.05 PACKAGE=wodan-irmin
# Failure to link irmin-unix with encore.0.3.0
  - env: OCAML_VERSION=4.07 PACKAGE=wodan-irmin
os:
  - linux
